# Configuration file for the ML pipeline
# Example for hyperopt:
# {"type": "int" | "float", "min": value, "max": value, "step": value (optional)}
# {"type": "categorical", "choices": [value1, value2, ...]}

# Pipeline parameters
pipeline:
  text_vectorizer:
    features:
      - "receiver"
    transform_mode: "inplace"
    transform_suffix: "_vec"
    hyperparams:
      kbest: {"type": "int", "min": 50, "max": 200, "step": 5}

  random_forest:
    features:
      - "*_vec"
      - "amount"
    transform_mode: "replace"
    transform_suffix: ""
    hyperparams:
      max_depth: {"type": "int", "min": 10, "max": 30}
      n_estimators: {"type": "int", "min": 50, "max": 400, "step": 10}
      min_samples_split: {"type": "int", "min": 10, "max": 100}
      min_samples_leaf: {"type": "int", "min": 10, "max": 100}
      criterion: {"type": "choice", "choices": ["gini", "entropy"]}
      random_state: 42

# Training parameters
training:
  target_column: "category"
  n_splits: 5
  shuffle: false

# Optimization parameters
optimization:
  startup_jobs: 5
  max_evals: 50
  early_stop_patience: 10
  loss_metric: "f1_score_macro_mean"
  higher_is_better: true

# Data parameters
query:
  start_date:
  end_date:
  mock: false

# Evaluation parameters
metrics:
  accuracy:
    reducers: ["mean", "minmax"]
  precision_macro:
    reducers: ["mean", "minmax"]
  recall_macro:
    reducers: ["mean", "minmax"]
  f1_score_macro:
    reducers: ["mean", "minmax"]
  roc_auc_macro:
    reducers: ["mean", "minmax"]
  roc_auc_micro:
    reducers: ["mean", "minmax"]
