from typing import Protocol

import pandas as pd


class TransformerInterface(Protocol):
    def fit(self, X: pd.DataFrame, y: pd.Series = None) -> None: ...
    def transform(self, X: pd.DataFrame) -> pd.DataFrame: ...
    def fit_transform(self, X: pd.DataFrame, y: pd.Series = None) -> pd.DataFrame: ...
    @property
    def features(self) -> list: ...
