from typing import Protocol


class ModelInterface(Protocol):
    def fit(self, X, y) -> None: ...
    def predict(self, X): ...
    def predict_proba(self, X): ...
    @property
    def features(self) -> list: ...
